# Generated by Django 4.2.4 on 2023-08-15 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_fruit_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='fruit',
            name='link',
            field=models.CharField(default='ds', max_length=20),
            preserve_default=False,
        ),
    ]
