# Generated by Django 4.2.4 on 2023-08-15 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_fruit_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fruit',
            old_name='link',
            new_name='social_fb',
        ),
        migrations.AddField(
            model_name='fruit',
            name='social_tik',
            field=models.CharField(default='d', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fruit',
            name='social_twit',
            field=models.CharField(default='d', max_length=20),
            preserve_default=False,
        ),
    ]
