# Generated by Django 4.2.4 on 2023-08-16 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_link_fruit_social_fb_fruit_social_tik_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fruit',
            name='color',
        ),
        migrations.AddField(
            model_name='color',
            name='position',
            field=models.CharField(default='d', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='color',
            name='size',
            field=models.CharField(default='d', max_length=20),
            preserve_default=False,
        ),
    ]
