# Generated by Django 4.2.4 on 2023-08-16 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_fruit_color_color_position_color_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='fruit',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fruits', to='app.color'),
        ),
    ]
