# Generated by Django 4.2.4 on 2023-08-16 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_fruit_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fruit',
            name='color',
        ),
        migrations.AddField(
            model_name='color',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='app.fruit'),
        ),
    ]
