# Generated by Django 4.2.4 on 2023-08-16 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_product_rename_fruit_user_delete_color_product_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='social_fb',
        ),
        migrations.RemoveField(
            model_name='user',
            name='social_tik',
        ),
        migrations.RemoveField(
            model_name='user',
            name='social_twit',
        ),
    ]
